markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: 宋小寅                                             # 博客名称
    description: 个人博客                                     # 博客描述
    title: 宋                                               # 网页标题
    url: xiaoyinsong.github.io                # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: 宋小寅                                       # 作者名称
    email: 398088199@qq.com                                # 邮箱地址
    weibo: http://weibo.com/xiaoyinsong                   # 微博地址
    github: https://github.com/xiaoyinsong/              # GitHub地址
    logo:                                                # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
